### ISSUE TITLE
Answer to https://github.com/82munk

### ISSUE THREAD

**Issue by ELynx** [ELynx/ddf-350-modding#2]
![20240704_130955.jpg](https://github.com/ELynx/ddf-350-modding/assets/174704962/972938f0-af62-4dbf-9a18-79aa33872bf5)

The files bin files from dumbo are not recognised by PowerIso or 7zip or do i need another program? 
Your patches look fine

What drivers do i need ddf350 & pc i get not recognised pop up

_Originally posted by @82munk in https://github.com/ELynx/ddf-350-modding/issues/1#issuecomment-2208857595_

**Comment by 82munk** [comment]
How do i find it?  Idk github

**Comment by ELynx** [comment]
Wait man, I am writing :)

**Comment by ELynx** [comment]
Since you are online now, can you tell me what you want to do with 7zip?

**Comment by 82munk** [comment]
Your mod & patch are fine, all the bin. files from dumbo are not recognised by PowerIso or 7zip, am i missing driver's?

**Comment by ELynx** [comment]
OK, what have you tried in following these steps?
https://github.com/ELynx/ddf-350-modding?tab=readme-ov-file#how-to-install
At what step exactly you need 7zip?

I just tried 7zip on original .zip file and fresh download of 7zip, opened fine for me.
So, you take original .zip, extract somewhere. This is only step you need 7zip or any other .zip file.

Then you use LunarIPS, it is path on .bin.

You do not need to zip it back, or anything. Once .bin is patched, you just run .bat file near it.

For drivers: none that I know of. Take out any and all batteries, connect to USB, press CH3 and CH4, then power.

**Comment by ELynx** [comment]
OK, I see no follow-up, hope it helped, closing.

**Comment by ELynx** [comment]
Also did a video on how to do it
https://www.youtube.com/watch?v=8Tg5iURBdxE
